<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WindowsMonitor.Core\WindowsMonitor.Core.csproj" />
    <ProjectReference Include="..\WindowsMonitor.Infrastructure\WindowsMonitor.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AntdUI" Version="2.4.1" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\app.ico" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\app.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
